### PR TITLE
Better looks in macOS in SwiftUI

### PR DESCRIPTION
**Pull request by urayoanm**
Better look with macOS in SwiftUI

### CODE REVIEW

**Comment by fethica** [comment]
Thanks for the update @urayoanm !

**Comment by fethica** [comment]
Hey @urayoanm, I did minor updates to the SwiftUI example app and the FRadioPlayer library, let me know if you have any issues, I'll probably publish the new version tomorrow 👍 Thanks!

**Comment by urayoanm** [comment]
It looks more consistent. Thanks!

**Comment by urayoanm** [comment]
Oh and running the code is much more elegant :). Thank you very much again

**Comment by fethica** [comment]
@urayoanm version 0.1.21 is out 🎉 thanks a lot for your contributions 👍

Twitter announcement: https://twitter.com/fethica/status/1336848850640834561

**Pull request merged**
